apiVersion: apps/v1
kind: Deployment
metadata:
  name: organic-deployment
  namespace: adi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organic
  template:
    metadata:
      labels:
        app: organic
    spec:
      containers:
        - name: organic-container
          image: adi0901/organic:v1
          ports:
            - containerPort: 5656
