apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.mongodb.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.servicePort }}
      targetPort: {{ .Values.mongodb.port }}
